//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccidentRepost
{
    using System;
    using System.Collections.Generic;
    
    public partial class events
    {
        public int id { get; set; }
        public string lat { get; set; }
        public string lon { get; set; }
        public string video_url { get; set; }
        public string date { get; set; }
        public Nullable<bool> important { get; set; }
    }
}
